---
abstract: 'Build POD documentation like MARCEL'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Nigel Metheringham <nigel.metheringham@cpan.com>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-MARCEL
provides:
  Pod::Weaver::PluginBundle::MARCEL:
    file: lib/Pod/Weaver/PluginBundle/MARCEL.pm
    version: 1.102340
  Pod::Weaver::Section::Availability:
    file: lib/Pod/Weaver/Section/Availability.pm
    version: 1.102340
  Pod::Weaver::Section::BugsAndLimitations:
    file: lib/Pod/Weaver/Section/BugsAndLimitations.pm
    version: 1.102340
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Role::Section: 0
  Pod::Weaver::Section::Installation: 0
  namespace::autoclean: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-PluginBundle-MARCEL
  homepage: http://search.cpan.org/dist/Pod-Weaver-PluginBundle-MARCEL/
  repository: http://github.com/hanekomu/Pod-Weaver-PluginBundle-MARCEL
version: 1.102340
